port: 5000
triggers:
  - id: my-service-prod
    token: my-access-token-1
    script: /home/brickpop/deploy-prod.sh
    timeout: 600
  - id: my-service-dev
    token: my-access-token-2
    script: /home/brickpop/deploy-prod.sh
