name: Builder
on: 
  push: 
    branches: 
    — main
  pull_request: 
    branches: 
    — main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.3' # The Go version to download (if necessary) and use.
    
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    - name: Run build
      run: go build -o dist/webtrigger 
    
    - name: Archive binary
      uses: actions/upload-artifact@v2
      with:
        name: webtrigger
        path: dist

    - name: Run vet & lint
      run: |
        go vet .
        golint .
    
    - name: Run testing
      run: cd test && go test -v
    